version: "3.8"

services:
  mongo:
    image: mongo
    container_name: roshani-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /Users/thakr/Desktop/data:/data/db

  mongo-express:
    image: mongo-express
    container_name: roshani-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  node-app:
    build: .
    container_name: roshani-node-app
    ports:
      - "2020:2020"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - mongo
